language: java
jdk:
  - oraclejdk8
notifications:
  email:
    recipients:
      - uo174348@uniovi.es
    on_success: never
    on_failure: always
before_install:
  - pip install --user codecov
after_success:
  - codecov
